apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
spec:
  type: LoadBalancer  # Can be NodePort or ClusterIP depending on your setup
  selector:
    app: petclinic
  ports:
    - protocol: TCP
      port: 80           # External port
      targetPort: 8080    # Internal port of the container

